name: isolate_manager
description: Create multiple long-lived isolates for the Functions, supports Worker on the Web (with the effective generator) and WASM compilation.
version: 5.4.0
homepage: https://github.com/lamnhan066/isolate_manager

topics:
  - isolate
  - worker
  - concurrent

environment:
  sdk: ^3.4.0

dependencies:
  analyzer: ">=5.12.0 <7.0.0"
  args: ^2.5.0
  path: ^1.9.0
  stream_channel: ^2.1.2
  web: ">=0.5.1 <2.0.0"

dev_dependencies:
  test: ^1.25.8
  very_good_analysis: ^6.0.0
